/** Shared authored CUI appearance, independent of StarterGui and live game state. */
export namespace ViewDefaults {
	// @outline SETTINGS

	export const Frame = {
		LayoutOrder: 0,
		AnchorPoint: new Vector2(0, 0),
		Position: UDim2.fromScale(0, 0),
		Size: UDim2.fromScale(1, 1),
		SizeConstraint: Enum.SizeConstraint.RelativeXY,
		AutomaticSize: Enum.AutomaticSize.None,
		Rotation: 0,
		ZIndex: 1,
		Visible: true,
		BackgroundColor3: Color3.fromRGB(255, 255, 255),
		BackgroundTransparency: 0,
		BorderColor3: Color3.fromRGB(0, 0, 0),
		BorderSizePixel: 0,
		BorderMode: Enum.BorderMode.Outline,
		ClipsDescendants: false,
		Active: false,
		Interactable: true,
		Selectable: false,
		SelectionOrder: 0,
		AutoLocalize: true,
		Style: Enum.FrameStyle.Custom,
	} as const;

	export const UIListLayout = {
		FillDirection: Enum.FillDirection.Vertical,
		HorizontalAlignment: Enum.HorizontalAlignment.Left,
		VerticalAlignment: Enum.VerticalAlignment.Top,
		SortOrder: Enum.SortOrder.LayoutOrder,
		Padding: new UDim(0, 0),
		HorizontalFlex: Enum.UIFlexAlignment.None,
		VerticalFlex: Enum.UIFlexAlignment.None,
		ItemLineAlignment: Enum.ItemLineAlignment.Automatic,
		Wraps: false,
	} as const;

	export const TextLabel = {
		LayoutOrder: 0,
		AnchorPoint: new Vector2(1, 0.5),
		Position: UDim2.fromScale(1, 0.5),
		Size: new UDim2(1, -6, 1, 0),
		SizeConstraint: Enum.SizeConstraint.RelativeXY,
		AutomaticSize: Enum.AutomaticSize.None,
		Rotation: 0,
		ZIndex: 10,
		Visible: true,
		BackgroundColor3: Color3.fromRGB(255, 255, 255),
		BackgroundTransparency: 1,
		BorderColor3: Color3.fromRGB(0, 0, 0),
		BorderSizePixel: 0,
		BorderMode: Enum.BorderMode.Outline,
		ClipsDescendants: false,
		Active: false,
		Interactable: true,
		Selectable: false,
		SelectionOrder: 0,
		AutoLocalize: true,
		FontFace: new Font("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
		Text: "Position Y",
		TextSize: 14,
		TextColor3: Color3.fromRGB(229, 229, 229),
		TextTransparency: 0,
		TextStrokeColor3: Color3.fromRGB(0, 0, 0),
		TextStrokeTransparency: 1,
		RichText: false,
		TextWrapped: false,
		TextScaled: false,
		TextTruncate: Enum.TextTruncate.None,
		TextXAlignment: Enum.TextXAlignment.Left,
		TextYAlignment: Enum.TextYAlignment.Center,
		LineHeight: 1,
		MaxVisibleGraphemes: -1,
	} as const;

	export const TextButton = {
		LayoutOrder: 0,
		AnchorPoint: new Vector2(0, 0),
		Position: UDim2.fromScale(0, 0),
		Size: UDim2.fromScale(1, 1),
		SizeConstraint: Enum.SizeConstraint.RelativeXY,
		AutomaticSize: Enum.AutomaticSize.None,
		Rotation: 0,
		ZIndex: 100,
		Visible: true,
		BackgroundColor3: Color3.fromRGB(255, 255, 255),
		BackgroundTransparency: 1,
		BorderColor3: Color3.fromRGB(0, 0, 0),
		BorderSizePixel: 0,
		BorderMode: Enum.BorderMode.Outline,
		ClipsDescendants: false,
		Active: true,
		Interactable: true,
		Selectable: true,
		SelectionOrder: 0,
		AutoLocalize: true,
		Style: Enum.ButtonStyle.Custom,
		FontFace: new Font("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
		Text: "",
		TextSize: 14,
		TextColor3: Color3.fromRGB(0, 0, 0),
		TextTransparency: 0,
		TextStrokeColor3: Color3.fromRGB(0, 0, 0),
		TextStrokeTransparency: 1,
		RichText: false,
		TextWrapped: false,
		TextScaled: false,
		TextTruncate: Enum.TextTruncate.None,
		TextXAlignment: Enum.TextXAlignment.Center,
		TextYAlignment: Enum.TextYAlignment.Center,
		LineHeight: 1,
		MaxVisibleGraphemes: -1,
		AutoButtonColor: true,
		Modal: false,
		Selected: false,
	} as const;

	export const ScrollingFrame = {
		LayoutOrder: 0,
		AnchorPoint: new Vector2(0, 0),
		Position: UDim2.fromScale(0, 0),
		Size: UDim2.fromScale(1, 1),
		SizeConstraint: Enum.SizeConstraint.RelativeXY,
		AutomaticSize: Enum.AutomaticSize.None,
		Rotation: 0,
		ZIndex: 9,
		Visible: true,
		BackgroundColor3: Color3.fromRGB(255, 255, 255),
		BackgroundTransparency: 1,
		BorderColor3: Color3.fromRGB(0, 0, 0),
		BorderSizePixel: 0,
		BorderMode: Enum.BorderMode.Outline,
		ClipsDescendants: true,
		Active: true,
		Interactable: true,
		Selectable: true,
		SelectionOrder: 0,
		AutoLocalize: true,
		CanvasSize: UDim2.fromScale(0, 2),
		AutomaticCanvasSize: Enum.AutomaticSize.None,
		CanvasPosition: new Vector2(0, 0),
		ScrollingDirection: Enum.ScrollingDirection.XY,
		ScrollingEnabled: true,
		ElasticBehavior: Enum.ElasticBehavior.WhenScrollable,
		ScrollBarThickness: 10,
		ScrollBarImageColor3: Color3.fromRGB(255, 255, 255),
		ScrollBarImageTransparency: 0,
		HorizontalScrollBarInset: Enum.ScrollBarInset.None,
		VerticalScrollBarInset: Enum.ScrollBarInset.Always,
		VerticalScrollBarPosition: Enum.VerticalScrollBarPosition.Right,
		TopImage: "rbxassetid://5168609593",
		MidImage: "rbxassetid://5168609593",
		BottomImage: "rbxassetid://5168609593",
	} as const;

	export const TextBox = {
		LayoutOrder: 0,
		AnchorPoint: new Vector2(1, 0.5),
		Position: new UDim2(1, 0, 0.5, -1),
		Size: UDim2.fromScale(1, 1),
		SizeConstraint: Enum.SizeConstraint.RelativeXY,
		AutomaticSize: Enum.AutomaticSize.None,
		Rotation: 0,
		ZIndex: 9000100,
		Visible: true,
		BackgroundColor3: Color3.fromRGB(255, 255, 255),
		BackgroundTransparency: 1,
		BorderColor3: Color3.fromRGB(0, 0, 0),
		BorderSizePixel: 0,
		BorderMode: Enum.BorderMode.Outline,
		ClipsDescendants: false,
		Active: true,
		Interactable: true,
		Selectable: true,
		SelectionOrder: 0,
		AutoLocalize: true,
		FontFace: new Font("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
		Text: "01",
		TextSize: 14,
		TextColor3: Color3.fromRGB(229, 229, 229),
		TextTransparency: 0,
		TextStrokeColor3: Color3.fromRGB(0, 0, 0),
		TextStrokeTransparency: 1,
		RichText: false,
		TextWrapped: false,
		TextScaled: false,
		TextTruncate: Enum.TextTruncate.None,
		TextXAlignment: Enum.TextXAlignment.Center,
		TextYAlignment: Enum.TextYAlignment.Center,
		LineHeight: 1,
		MaxVisibleGraphemes: -1,
		ClearTextOnFocus: true,
		MultiLine: false,
		PlaceholderText: "",
		PlaceholderColor3: new Color3(0.7, 0.7, 0.7),
		ShowNativeInput: true,
		TextEditable: true,
	} as const;

	export const ViewportFrame = {
		LayoutOrder: 0,
		AnchorPoint: new Vector2(0, 0),
		Position: UDim2.fromScale(0, 0),
		Size: UDim2.fromScale(1, 1),
		SizeConstraint: Enum.SizeConstraint.RelativeXY,
		AutomaticSize: Enum.AutomaticSize.None,
		Rotation: 0,
		ZIndex: 1,
		Visible: true,
		BackgroundColor3: Color3.fromRGB(0, 0, 0),
		BackgroundTransparency: 0.75,
		BorderColor3: Color3.fromRGB(0, 0, 0),
		BorderSizePixel: 0,
		BorderMode: Enum.BorderMode.Outline,
		ClipsDescendants: false,
		Active: false,
		Interactable: true,
		Selectable: false,
		SelectionOrder: 0,
		AutoLocalize: true,
		ImageColor3: Color3.fromRGB(255, 255, 255),
		ImageTransparency: 0,
		Ambient: Color3.fromRGB(200, 200, 200),
		LightColor: Color3.fromRGB(140, 140, 140),
		LightDirection: new Vector3(-1, -1, -1),
	} as const;

	export const UIAspectRatioConstraint = {
		AspectRatio: 1,
		AspectType: Enum.AspectType.FitWithinMaxSize,
		DominantAxis: Enum.DominantAxis.Width,
	} as const;

	export const ImageLabel = {
		LayoutOrder: 0,
		AnchorPoint: new Vector2(0.5, 0.5),
		Position: UDim2.fromScale(0.5, 0.5),
		Size: UDim2.fromScale(0.8, 0.8),
		SizeConstraint: Enum.SizeConstraint.RelativeXY,
		AutomaticSize: Enum.AutomaticSize.None,
		Rotation: 0,
		ZIndex: 1,
		Visible: true,
		BackgroundColor3: Color3.fromRGB(255, 255, 255),
		BackgroundTransparency: 1,
		BorderColor3: Color3.fromRGB(0, 0, 0),
		BorderSizePixel: 0,
		BorderMode: Enum.BorderMode.Outline,
		ClipsDescendants: false,
		Active: false,
		Interactable: true,
		Selectable: false,
		SelectionOrder: 0,
		AutoLocalize: true,
		Image: "rbxassetid://80986199235506",
		ImageColor3: Color3.fromRGB(255, 255, 255),
		ImageTransparency: 0,
		ImageRectOffset: new Vector2(0, 0),
		ImageRectSize: new Vector2(0, 0),
		ScaleType: Enum.ScaleType.Stretch,
		ResampleMode: Enum.ResamplerMode.Default,
		SliceCenter: new Rect(0, 0, 0, 0),
		SliceScale: 1,
		TileSize: UDim2.fromScale(1, 1),
	} as const;

	export const UIStroke = {
		ApplyStrokeMode: Enum.ApplyStrokeMode.Contextual,
		Color: Color3.fromRGB(0, 0, 0),
		Enabled: true,
		LineJoinMode: Enum.LineJoinMode.Round,
		Thickness: 1,
		Transparency: 0,
		StrokeSizingMode: Enum.StrokeSizingMode.FixedSize,
	} as const;

	export const UICorner = {
		CornerRadius: new UDim(0, 4),
	} as const;

	export const UIGradient = {
		Rotation: 0,
		Color: new ColorSequence([
			new ColorSequenceKeypoint(0, Color3.fromRGB(0, 0, 0)),
			new ColorSequenceKeypoint(1, Color3.fromRGB(255, 0, 0)),
		]),
		Enabled: true,
		Transparency: new NumberSequence([new NumberSequenceKeypoint(0, 0, 0), new NumberSequenceKeypoint(1, 0, 0)]),
		Offset: new Vector2(0, 0),
	} as const;

	export const UIFlexItem = {
		ItemLineAlignment: Enum.ItemLineAlignment.Automatic,
		FlexMode: Enum.UIFlexMode.Fill,
		GrowRatio: 0,
		ShrinkRatio: 0,
	} as const;

	export const UIPadding = {
		PaddingTop: new UDim(0, 0),
		PaddingBottom: new UDim(0, 0),
		PaddingLeft: new UDim(0, 0),
		PaddingRight: new UDim(0, 4),
	} as const;

	export const UIGridLayout = {
		FillDirection: Enum.FillDirection.Horizontal,
		HorizontalAlignment: Enum.HorizontalAlignment.Left,
		VerticalAlignment: Enum.VerticalAlignment.Top,
		SortOrder: Enum.SortOrder.Name,
		CellPadding: UDim2.fromScale(0, 0),
		CellSize: new UDim2(1, 0, 0, 18),
		FillDirectionMaxCells: 0,
		StartCorner: Enum.StartCorner.TopLeft,
	} as const;

	// @outline FUNCTIONS

	export function Attributes(Values: Record<string, string>) {
		return (Target: Instance) => {
			for (const [Key, Value] of pairs(Values)) Target.SetAttribute(Key, Value);
		};
	}
}
